### ISSUE TITLE
httptools.parser.errors.HttpParserInvalidURLError: invalid URL

### ISSUE THREAD

**Issue by messense** [bosondata/chrome-prerender#10]
```
2017-05-17 23:38:33 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/prerender/venv/lib/python3.6/site-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidURLError: invalid URL
2017-05-17 23:38:33,870 ERROR sanic.log:104   Traceback (most recent call last):
  File "/home/prerender/venv/lib/python3.6/site-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidURLError: invalid URL
```

**Comment by messense** [comment]
```
"GET /https://www.riskstorm.com/company/\xE4\xBC\x81\xE5\x90\x88\xE5\x9B\xBD\xE5\xAD\x97\xE7\xAC\xAC000390 HTTP/1.1" 400 18 0.113 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36; 360Spider"
```

WTF

**Comment by messense** [comment]
https://github.com/nodejs/http-parser/issues/26

**Comment by messense** [comment]
https://github.com/nodejs/http-parser/issues/132

**Comment by messense** [comment]
Can't fix in here.
