### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by sarpavci** [bosondata/chrome-prerender#18]
I install prerender via `pip3 install -U prerender` and run `prerender` commmand in cli. I get the following error:
``` bash
root@Prerender-3:~# prerender
Traceback (most recent call last):
  File "/usr/local/bin/prerender", line 7, in <module>
    from prerender.cli import main
  File "/usr/local/lib/python3.5/dist-packages/prerender/cli.py", line 8
    DEBUG: bool = os.environ.get('DEBUG', 'false').lower() in ('true', 'yes', '1')
         ^
SyntaxError: invalid syntax
```

**Comment by messense** [comment]
You need to run it using Python 3.6+

发自我的 iPhone

**Comment by sarpavci** [comment]
Thanks @messense i will try it
