### ISSUE TITLE
Install fail on Centos 7 using pip

### ISSUE THREAD

**Issue by olidietzel** [bosondata/chrome-prerender#34]
Do i need to install python3 and/or something else?

[root@prerender ~]# pip install prerender
Collecting prerender
  Using cached prerender-0.9.3.tar.gz
Collecting websockets (from prerender)
  Using cached websockets-4.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_SAdD7/websockets/setup.py", line 11, in <module>
        with open(readme_file, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_SAdD7/websockets/

**Comment by olidietzel** [comment]
Worked by installing python3 and pip3 following these howtos:

https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7

https://stackoverflow.com/questions/11268501/how-to-use-pip-with-python-3-x-alongside-python-2-x
